### ISSUE TITLE
Description, lack of screenshots

### ISSUE THREAD

**Issue by rsxdalv** [wretched-tui/wretched#3]
The description almost makes it sound like you used React to render a console, I recommend making it clearer that React/components is the idea behind the UI architecture rather than actually utilizing React as a console UI.

Also, due to the lack of screenshots it's hard to grasp this project, even if I know _blessed_ and understand conceptually what it should look like.

Finally, is the idea to support jsx/tsx compilation at some point? It seems like it could almost be transpiled from JSX to wretched-tui.

**Comment by colinta** [comment]
These are great tips! I thought I would get around to implementing some or all of these but haven't yet - wanted to let you know I saw this and I'm keeping it marked "TODO". 

👍

**Comment by colinta** [comment]
OK getting back to this, you'll want to look at https://github.com/wretched-tui/wretched-react which implements a renderer for wretched components. This separation is delibrate - wretched is the "DOM" so to speak, wretched-react leverages React as a manager for that component tree. (and I'll try to clarify the docs, and add some screenshots)

**Comment by rsxdalv** [comment]
Great job!
Although I'm guessing the answer is yes, does this mean it can also be
bundled as a standalone js file using browserify or similar old tools?

**Comment by colinta** [comment]
Browserify- maybe? I guess I don't know why you *would* - but yes it can be used standalone.
